---
apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: books-db
  labels:
    env: dev
    app: books-db
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: books-db
  template:
    metadata:
      labels:
        app: books-db
    spec:
      containers:                     
      - image: postgres:15-alpine
        name: books-db
        env: 
          - name: POSTGRES_USER
            value: user
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: booksdb
        resources:                    
          requests:
            memory: 24Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 500m

---
apiVersion: v1 
kind: Service 
metadata:
  name: books-db-svc
spec:
  selector:
    app: books-db
  ports:
    - port: 5432                   # Port exposed by the service
      targetPort: 5432             # Port on the container that receives traffic